# Generated by Django 6.1 on 2026-08-22 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0002_socio_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='socio',
            name='altura',
            field=models.FloatField(blank=True, help_text='Altura en cm', null=True),
        ),
        migrations.AddField(
            model_name='socio',
            name='condiciones_medicas',
            field=models.TextField(blank=True, default='', help_text='Lesiones, condiciones médicas, alergias, etc.'),
        ),
        migrations.AddField(
            model_name='socio',
            name='nivel_actividad',
            field=models.CharField(blank=True, choices=[('sedentario', 'Sedentario (poco o nada de ejercicio)'), ('principiante', 'Principiante (< 6 meses)'), ('intermedio', 'Intermedio (6 meses - 2 años)'), ('avanzado', 'Avanzado (> 2 años)')], default='principiante', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='socio',
            name='objetivo',
            field=models.CharField(blank=True, choices=[('ganar_musculo', 'Ganar masa muscular'), ('perder_peso', 'Perder grasa'), ('mantenerse', 'Mantenimiento'), ('resistencia', 'Mejorar resistencia'), ('flexibilidad', 'Mejorar flexibilidad'), ('salud', 'Salud general')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='socio',
            name='peso',
            field=models.FloatField(blank=True, help_text='Peso en kg', null=True),
        ),
    ]
