# Generated by Django 6.1 on 2026-08-28 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0003_socio_altura_socio_condiciones_medicas_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socio',
            name='usuario',
        ),
    ]
